### ISSUE TITLE
Build Out basic Routing 

### ISSUE THREAD

**Issue by JeffQuit** [jonnikim/Project2Scheduler#10]

**Comment by jonnikim** [comment]
- Refer to Microsoft Tutorial App on how to implement Azure into routing.

**Comment by jonnikim** [comment]
Admin: - "/" - index page
           | - 'user/login' - takes you to the log in page
           | - 'user/register' - takes to to the page to register
           | - "user/schedule" - Admin schedule view once logged in/authenticated
Client: - "/NewEvent" - page to create a new event from an invite link
         | - "/NewEventConf" - Confirmation Page for new event

 two folders: Admin & Client. Admin will contain the UI for the log in launch page and the admin view scheduler. The Client folder will contain the pages for the set up new event process
