### ISSUE TITLE
Create Database Tables via Seuqlize 

### ISSUE THREAD

**Issue by JeffQuit** [jonnikim/Project2Scheduler#6]
Table for User
Table for Appointments
Table for Availability

**Comment by jonnikim** [comment]
full calendar table  
{
    "id": "999",
    "title": "Long Event",
    "start": "2020-06-07",
    "end": "2020-06-10"
  },

**Comment by JeffQuit** [comment]
**Three Tables:**
User (used for creating account)
Event (used for logging events into the calendar
Invite (Used for issuing new invite codes:



**Table Schema - User**
ID (primary Key & Auto Incrementing)
first_name DataTypes.STRING, Not Null
last_name DataTypes.STRING, Not Null
email DataTypes.STRING, Not Null
password DataTypes.STRING, Not Null
is_admin Boolean

Associations:
User has many invite and events

SEQUELIZE CODE:
npx sequelize-cli model:generate --name User --attributes first_name:string,last_name:string,email:string,password:string,is_admin:boolean




**Table Schema - Event**

id: ID (primary Key & Auto Incrementing)
title: 'Test Event Formatting', DataTypes.STRING, Not Null
start: '2020-07-23T11:00:00', DataTypes.STRING, Not Null
end: '2020-07-23T12:00:00', DataTypes.STRING, Not Null
constraint: 'businessHours', - Not sure if we need this
admin_id: '', - Assoicated to User.ID
first_name: '', - DataTypes.STRING, Not Null
last_name: '', -DataTypes.STRING, Not Null
email: '', - DataTypes.STRING, Not Null
if1: '', - DataTypes.STRING, Not Null
if2: '', - DataTypes.STRING, Not Null
itf: '', - DataTypes.TEXT, Not Null
invite_ID: associated with invite.id
invite_code: associated with invite.invite_code

Associations:
Event belongs to user
Foreign Key - admin_id

SEQUELIZE CODE:
npx sequelize-cli model:generate --name Event --attributes title:string,start:string,end:string,constraint:string,admin_id:integer,first_name:string,last_name:string,email:string,if1:string,if2:string,Ift:text,invite_id:integer,invite_code:integer 




Event belongs to invite
foreign Key - invite_ID &/Or invite_code

Table Schema - Invite *we will need this to issue invite links*
ID - Primary Key Auto Increment Not Null
Invite_Code - integer Not Null
admin_id - associted with user.ID of who sent the invite
first_name - recipient of email - string
last_name - recipent of email - string
email - recipient of email - string

Associations:
invite belongs to user
Foreign Key - admin_id

**SEQUELIZE CODE:**
npx sequelize-cli model:generate --name Invite --attributes invite_code:integer,admin_id:integer,first_name:string,last_name:string,email:string

**Comment by JeffQuit** [comment]
The models have been created, we just need to add validation and associations to them
