### ISSUE TITLE
Research Office 365 Email API 

### ISSUE THREAD

**Issue by JeffQuit** [jonnikim/Project2Scheduler#8]
Need to create Email API to confirm appointment and to send invite to schedule appointment

**Comment by jonnikim** [comment]
https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Javascript#AuthCodeProvider

https://docs.microsoft.com/en-us/graph/tutorials/node

https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=javascript

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md

**Comment by jonnikim** [comment]
https://github.com/microsoftgraph/msgraph-training-nodeexpressapp

**Comment by jonnikim** [comment]
https://www.youtube.com/watch?v=Sx46yCYPsek
https://www.youtube.com/watch?v=n6q8Cm-pTYY&feature=emb_title

https://portal.azure.com/#home

**Comment by jonnikim** [comment]
**Current:**
- Requires a free subscription to Azure. CC info necessary, but doesn't require a paid subscription.
- Ask Omar/TAs for clarification on "secrets", and overall experience with Azure.
- Able to setup account on Azure + necessary permissions.

**Upcoming:**
- Look up more video tutorials
- How does this fit in our MVC paradigm?

**Comment by jonnikim** [comment]
Able to setup Azure Tutorial App w/email login functionality.
